import jsPDF from "jspdf";

function loadImage(src) {
  return new Promise((resolve, reject) => {
    if (!src) {
      resolve(null);
      return;
    }

    const img = new Image();
    img.crossOrigin = "Anonymous";

    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("Unable to load image"));

    img.src = src;
  });
}

function imageToDataURL(image) {
  const canvas = document.createElement("canvas");

  canvas.width = image.width;
  canvas.height = image.height;

  const ctx = canvas.getContext("2d");
  ctx.drawImage(image, 0, 0);

  return canvas.toDataURL("image/png");
}

function formatValue(value, fallback = "--") {
  if (value === null || value === undefined || value === "") {
    return fallback;
  }

  return value;
}

export async function generateReport({
  uploadedImage,
  outputImage,
  cloudCoverage,
  processingTime,
  resolution,
  model,
  device,
  timestamp,
}) {
  const pdf = new jsPDF("portrait", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();

  const reportId =
    "ANT-" +
    new Date()
      .toISOString()
      .replace(/[-:.TZ]/g, "")
      .substring(0, 14);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("ANTARISK ANALYSIS REPORT", pageWidth / 2, 18, {
    align: "center",
  });

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(
    "AI-Based Cloud Removal & Reconstruction",
    pageWidth / 2,
    26,
    {
      align: "center",
    }
  );

  pdf.line(15, 32, 195, 32);

  pdf.setFontSize(11);

  pdf.text(`Report ID : ${reportId}`, 15, 42);
  pdf.text(`Model : ${formatValue(model)}`, 15, 50);
  pdf.text(`Device : ${formatValue(device)}`, 15, 58);
  pdf.text(`Timestamp : ${formatValue(timestamp)}`, 15, 66);

  pdf.text(
    `Cloud Coverage : ${formatValue(cloudCoverage)}%`,
    110,
    42
  );

  pdf.text(
    `Processing Time : ${formatValue(processingTime)} sec`,
    110,
    50
  );

  pdf.text(
    `Resolution : ${
      resolution
        ? `${resolution.width} × ${resolution.height}`
        : "--"
    }`,
    110,
    58
  );

  pdf.text("Status : Reconstruction Successful", 110, 66);

  pdf.line(15, 74, 195, 74);

  pdf.setFont("helvetica", "bold");
  pdf.text("Original Image", 15, 84);

  pdf.text("Reconstructed Image", 110, 84);

  try {
    const original = await loadImage(uploadedImage);

    if (original) {
      pdf.addImage(
        imageToDataURL(original),
        "PNG",
        15,
        88,
        80,
        80
      );
    }
  } catch {}

  try {
    const reconstructed = await loadImage(outputImage);

    if (reconstructed) {
      pdf.addImage(
        imageToDataURL(reconstructed),
        "PNG",
        110,
        88,
        80,
        80
      );
    }
  } catch {}

  pdf.line(15, 178, 195, 178);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);

  pdf.text("Prediction Summary", 15, 188);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  pdf.text(
    "The uploaded satellite image was processed using the",
    15,
    198
  );

  pdf.text(
    "ANTARISK-Net generative reconstruction model to",
    15,
    205
  );

  pdf.text(
    "remove cloud-covered regions while preserving",
    15,
    212
  );

  pdf.text(
    "spatial structures and surface characteristics.",
    15,
    219
  );

  pdf.line(15, 235, 195, 235);

  pdf.setFontSize(10);

  pdf.text(
    "Generated by ANTARISK | ISRO Cloud Removal Framework",
    pageWidth / 2,
    245,
    {
      align: "center",
    }
  );

  pdf.text(
    "© 2026 ANTARISK Research Team",
    pageWidth / 2,
    252,
    {
      align: "center",
    }
  );

  pdf.save(`ANTARISK_Report_${reportId}.pdf`);
}